# Generated by Django 4.0.5 on 2022-08-02 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=50)),
                ('commenterimg', models.ImageField(blank=True, default='profile.png', upload_to='commenterimg')),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(max_length=500)),
                ('commenter_email', models.CharField(blank=True, default='default_email', max_length=50)),
            ],
        ),
    ]
