# Generated by Django 4.0.5 on 2022-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commented_post',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
