# Generated by Django 4.0.5 on 2022-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0002_comments_commented_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commented_post',
            field=models.IntegerField(default='1'),
        ),
    ]
