# Generated by Django 4.0.5 on 2022-08-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0003_alter_comments_commented_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_number',
            field=models.IntegerField(default='0'),
        ),
    ]
