# Generated by Django 4.0.5 on 2022-08-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0004_comments_comment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_number',
        ),
    ]
