# Generated by Django 4.0.5 on 2022-08-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='author',
            new_name='user',
        ),
    ]
