# Generated by Django 4.0.5 on 2022-08-01 14:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_author_articles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body_long',
            field=ckeditor.fields.RichTextField(default='long text here', max_length=5000),
        ),
    ]
