# Generated by Django 4.0.5 on 2022-08-03 10:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articles_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=231),
        ),
    ]
