# Generated by Django 4.0.5 on 2022-08-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articles_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comment_number',
            field=models.IntegerField(default='0'),
        ),
    ]
