# Generated by Django 4.0.5 on 2022-08-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_comment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='comment_number',
        ),
    ]
