# Generated by Django 4.0.5 on 2022-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='commented_length',
            field=models.BigIntegerField(default=0),
        ),
    ]
