# Generated by Django 4.0.5 on 2022-07-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='backgroundimg',
        ),
    ]
