# Generated by Django 4.0.5 on 2022-08-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
